### ISSUE TITLE
看起来这个是Python 3.8才能用？

### ISSUE THREAD

**Issue by LzNOHentai** [kumaneru/nicoxml2ass#1]
xml2ass_packet.py在3.7、3.6、2.7都报错，问题出在“ := ”这个符号上。
搜了一下似乎是3.8才新加的用法，升级成3.8正常使用。

**Comment by x15120** [comment]
感谢反馈。我这边没注意这个是不是3.8新加的，直接抄过来了。2.7是比较确定不能用的，所以只在readme里写了要求python 3.x

**Comment by x15120** [comment]
弃用了":="，可以再尝试一下3.7版本能不能用。2.7就不管了，确实该升级了（x
