### ISSUE TITLE
现在nico逐渐推广1080P生放送，弹幕ass能否兼容该分辨率？

### ISSUE THREAD

**Issue by LzNOHentai** [kumaneru/nicoxml2ass#3]
目前弹幕ass的分辨率还是720P：
PlayResX: 1280
PlayResY: 720

这样的弹幕在1080P视频中显得字体偏大了。当然也不可能就改这个完事，所有弹幕的定位都要统一调整了。
能否在转换的时候做个选项，自行选择对应1080 or 720？

**Comment by kumaneru** [comment]
可以描述得更具体一点吗？不管是1080p(nico6M)还是450p(nico1M/2M)，直接拿720p的弹幕压都会经过等比缩放，应该和压720p时占的画面比例一样，理论上不会导致在1080p视频中显得字体更大

**Comment by LzNOHentai** [comment]
这是一个1920*1080分辨率的视频，ニコ生 新配信録画ツール 抓取的xml弹幕，最新版本脚本转换的ass。
播放器为最新版Potplayer，渲染器madVR，字幕渲染滤镜xy-subfilters（核心为libass的mod版本）

上图是原本的ass（PlayResX: 1280, PlayResY: 720）
下图是直接使用文本编辑器将PlayRes改为1920和1080的ass。
![QQ截图20210911194640](https://user-images.githubusercontent.com/22359967/132946930-0f0449db-01de-4094-8e5d-e99533e54b8c.jpg)
![QQ截图20210911194728](https://user-images.githubusercontent.com/22359967/132946935-76e29994-76f4-48e2-bd38-c7ac2d4cb57a.jpg)

**Comment by kumaneru** [comment]
看了一下，1080P视频和720P视频应用相同的ass（PlayResX: 1280, PlayResY: 720）时每行所占的画面比例相同，无法理解字号偏大与分辨率的相关性。您可以自行对danmakuSize和limitLineAmount两个参数进行调整以适应使用习惯，这边目前没有统一更改的计划…

**Comment by LzNOHentai** [comment]
> 看了一下，1080P视频和720P视频应用相同的ass（PlayResX: 1280, PlayResY: 720）时每行所占的画面比例相同，无法理解字号偏大与分辨率的相关性。您可以自行对danmakuSize和limitLineAmount两个参数进行调整以适应使用习惯，这边目前没有统一更改的计划…

好吧，感谢回复。
我本意是想说能不能在如图 PlayResX: 1920, PlayResY: 1080 那种字体相对画面的大小下，让弹幕正确从屏幕边缘开始运动，且铺满屏幕。不过想想N站本身的播放器里好像就是720那种大小和样式，大概不太好弄吧。

**Comment by kumaneru** [comment]
xml转换成ass毕竟是模拟弹幕的样式，要模拟得更好感觉也不是不行，只不过ass的实现和nico播放器的实现还是有差距，细化这一部分的预期投入和预期回报差距有点大
